# Generated by Django 6.0.3 on 2026-03-10 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='crop_type',
            field=models.CharField(choices=[('Cacao', 'Cacao'), ('Rice', 'Rice'), ('Banana', 'Banana'), ('Vegetables', 'High-value Vegetables')], default='Rice', max_length=50),
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField()),
                ('soil_temperature', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('leaf_wetness', models.FloatField()),
                ('threat_level', models.CharField(default='Low', max_length=10)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farm.farm')),
            ],
        ),
    ]
