# Generated by Django 6.0.3 on 2026-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farm_created_at_farm_crop_type_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='threat_level',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
