# Generated by Django 6.0.3 on 2026-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_sensordata_threat_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crop_type',
            field=models.CharField(max_length=100),
        ),
    ]
